Refactor to new namespace scheme
Certain namespaces have been revised to better group functions that have
similar purpose:

`load` (formerly `conditions`) is for functions that apply loading
conditions to a model.

`math` is for functions that manipulate sequences of numeric values,
such as making a sequence denser or creating a log-biased sequence.

`mesh` is for functions that create meshes given a desired geometry and
a set of parameters.  It no longer has separate submodules for different
mesh element types, as there were too few functions to merit multiple
submodules.

`select` (formerly `selection`) is for functions that do complex lookup,
like `find_closest_timestep` or `surface_faces`.

`util` is for tool-like functions, such as mesh editing functions, that
modify febtools data structures.

Also, `test_selection.py` started being picked up by nosetest (it wasn't
run before) for some reason.  It failed with:

    AttributeError: 'XpltReader' object has no attribute 'f'

I want to get rid of `XpltReader` anyway, so I deleted
`test_selection.py`.

Tests pass.