Remove fixed charge density from fixture's output
FEBio doesn't define a fixed charge density variable for biphasic
simulations.  It's unclear when it does.  FEBio 2 would ignore the extra
variable, but FEBio 3 is more strict and raises an error:

FATAL ERROR: Output variable "fixed charge density" is not defined